import { Inter_Tight } from 'next/font/google';
import './globals.css';
import Navbar from './Components/Navbar';
import Banner from './Components/Banner';
import Footer from './Components/Footer';

// Load the Inter Tight font
const interTight = Inter_Tight({
  subsets: ['latin'],
  variable: '--font-inter-tight', // You can change this if needed
  weight: ['400', '500', '600', '700'], // Specify only the weights you use
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={interTight.className}>
        <div className='max-w-[1200px] mx-auto'>
           <Navbar></Navbar>
        </div>
        <div>{children}</div>
        <div className='mt-20 bg-[#030712]'>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
